org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=false
org.gradle.daemon=false
android.suppressUnsupportedCompileSdk=36
kotlin.compiler.execution.strategy=in-process
